<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use ShopBundle\Entity\Order;
use ShopBundle\Entity\OrderStatus;
use ShopBundle\Entity\User;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param EntityManagerInterface $em
     */

    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new \Doctrine\ORM\Mapping\ClassMetadata(Order::class));
    }

    /**
     * @param Order $order
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save(Order $order){
        $this->_em->persist($order);
        $this->_em->flush();
    }

    public function findOneByStatus(OrderStatus $status,User $user){
        return $this->findOneBy(['status'=>$status,'user'=>$user]);
    }

    public function findAllOrders(){
        return $this->findBy(array(),array('date_created'=>'DESC'));
    }
}
