<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use ShopBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param EntityManagerInterface $em
     */

    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new \Doctrine\ORM\Mapping\ClassMetadata(Product::class));
    }

    public function findAllInStock(){
        $q = $this->createQueryBuilder('p')
            ->where('p.quantity > :inStock')
            ->andWhere('p.isListed = :isListed')
            ->setParameter('inStock', 0)
            ->setParameter('isListed', 1)
            ->getQuery();

        return $q->getResult();
    }

    /**
     * @param Product $product
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save(Product $product):void {
        $this->_em->persist($product);
        $this->_em->flush();
    }
}
