<?php

namespace ShopBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllInStock(){
        $q = $this->createQueryBuilder('p')
            ->where('p.quantity > :inStock')
            ->setParameter('inStock', 0)
            ->getQuery();

        return $q->getResult();
    }
}
