<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use ShopBundle\Entity\Promotion;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param EntityManagerInterface $em
     */

    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new \Doctrine\ORM\Mapping\ClassMetadata(Promotion::class));
    }

    /**
     * @param Promotion $promotion
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save(Promotion $promotion){
        $this->_em->persist($promotion);
        $this->_em->flush();
    }

    public function findAllByQueryBuilder()
    {
        return $this->createQueryBuilder('promotion')
            ->orderBy('promotion.endDate', 'asc');
    }

    public function findAllAvailableByQueryBuilder()
    {
        return $this->createQueryBuilder('promotion')
            ->andWhere('promotion.startDate < :date')
            ->andWhere('promotion.endDate > :date')
            ->setParameter('date', new \DateTime('now'))
            ->orderBy('promotion.endDate', 'asc');
    }
}
