<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use ShopBundle\Entity\Product;
use ShopBundle\Entity\Review;
use ShopBundle\Entity\User;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param EntityManagerInterface $em
     */

    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new \Doctrine\ORM\Mapping\ClassMetadata(Review::class));
    }

    public function findOneByProductAndUser(User $user, Product $product)
    {
        return $this->findOneBy([
            "author" => $user,
            "product" => $product
        ]);
    }

    /**
     * @param Review $review
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save(Review $review){
        $this->_em->persist($review);
        $this->_em->flush();
    }

    /**
     * @param Review $review
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function delete(Review $review){
        $this->_em->remove($review);
        $this->_em->flush();
    }


}
