<?php

namespace ShopBundle\Repository;

use ShopBundle\Entity\Role;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Adding roles in database on first run. Roles and their hierarchy are predefined in security.yml
     * This function should be used only once on first user registration.
     */
    public function setupFirstRunRoles()
    {

    }

}
