<?php

namespace ShopBundle\Repository;

/**
 * ShopOwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopOwnerRepository extends \Doctrine\ORM\EntityRepository
{
}
