app:
    resource: '@ShopBundle/Controller/'
    type: annotation

pageNotFound:
    path:  /{path}
    defaults: { _controller: ShopBundle:PageNotFound:pageNotFound, path: '' }
    requirements:
        path: .*